            <?php
                $http_type = ((isset($_SERVER['HTTPS']) && $_SERVER['HTTPS'] == 'on') || (isset($_SERVER['HTTP_X_FORWARDED_PROTO']) && $_SERVER['HTTP_X_FORWARDED_PROTO'] == 'https')) ? 'https://' :'http://';
                $url = str_replace('http://', $http_type, $url);
                $uno_url = $uno_conf['url'];
                $gpui_path = $uno_conf['path']['gpui'];
                $gpui_url = $uno_url.$gpui_path;
            ?>
            <div style="position: absolute;top: 50%;left: 50%;height: auto;width: auto;transform: translate(-50%, -50%);">
                <i class="fa fa-2x fa-spinner fa-spin" style="font-size:40px"></i>
            </div>
            <script data-ajax="true">
            var toUrl = '<?= $url?>';
            var accessToken = '';
            var updateLocation = '';
            var gpuiUrl = '<?= $gpui_url ?>';
	        var oldAccessToken = '<?= $accessToken ?>';
            var orderHistory = setInterval(function(){
                require.config({
                    paths: { gpui: gpuiUrl }
                });
                require(['gpui'], function(data) {
                    accessToken = data.params.accessToken;
                });
		if (accessToken) {
                    if(accessToken != oldAccessToken){
			toUrl=toUrl+"?logout=true"
		    }
                    clearInterval(orderHistory);
                    window.location.href=toUrl;
		}
            }, 500);
            </script>
