<div class="modal fade">
    <div class="modal-dialog">
        <div class="modal-content">
            <?php
                if ($enable_uno_mode) {
            ?>
            <div class="modal-header">
                <h4 class="modal-title"></h4>
            </div>
            <div class="modal-body ">
                <ul class="gapper-client-checkbox list-unstyled list-inline text-center">
                   <p>登录中 请稍等....</p>
                </ul>
                <div class="text-right"></div>
            </div>
            <?php
                $uno_url = $uno_conf['url'];
                $gpui_path = $uno_conf['path']['gpui'];
                $gpui_url = $uno_url.$gpui_path;
            ?>

            <script data-ajax="true">
            var accessToken = '';
            var updateLocation = '';
            var gpuiUrl = '<?= $gpui_url ?>';
            var lab_id = '';
            var interval = setInterval(function(){
                require.config({
                    paths: { gpui: gpuiUrl }
                });
                require(['gpui'], function(data) {
                    accessToken = data.params.accessToken;
                });
                if(accessToken){
                    $.post('ajax/gapper/auth/gapper/login-by-access-token', {'accessToken':accessToken}, function(response){
                        var getCurrentGroupIDCount = 0;
                        var getCurrentGroupID = setInterval(function(){
                            require.config({
                                paths: { gpui: gpuiUrl }
                            });
                            require(['gpui'], function(data) {
                                lab_id = data.params.labId;
                            });
                            getCurrentGroupIDCount++;
                            if (lab_id){
                                $.post('ajax/gapper/auth/gapper/change-group', {'group_id':lab_id}, function(response){
                                    window.location.reload();
                                });
                            }
                            if (getCurrentGroupIDCount > 4) {
                                window.location.reload();
                            }
                        }, 3000);
                    });
                    clearInterval(interval);
                }
            }, 500);
            </script>
            <?php
                } else {
            ?>
            <div class="modal-header">
                <h4 class="modal-title"><?=H('请选择登录方式:')?></h4>
            </div>
            <div class="modal-body ">
                <ul class="gapper-client-checkbox list-unstyled list-inline text-center">
                    <?php foreach ($sources as $source=>$info) {?>
                        <li class="<?= $info['url'] ? '' : 'gapper-client-checkbox-li'?>" data-gapper-auth-source="<?=H($source)?>">
                        <?php if ($info['url']) {?>
                            <a href="<?=$info['url']?>" style="display:inline-block;">
                        <?php } ?>
                            <div class="app-icon app-icon-hoverable">
                                <div class="app-icon-image"><img src="<?=H($info['icon'])?>" /></div>
                                <div class="app-icon-title"><?=H($info['name'])?></div>
                            </div>
                        <?php if ($info['url']) {?>
                            </a>
                        <?php }?>
                        </li>
                    <?php }?>
                </ul>
                <div class="text-right"><a href="<?= \Gini\URI::url('gapper/client/gohome')?>"><?= H(T('返回首页'))?></a></div>
            </div>
            <?php } ?>
        </div>
    </div>
</div>
