<div class="modal fade">
    <div class="modal-dialog add-member-modal">
        <div class="modal-content">
            <div class="modal-header">
                <button type="button" class="close" data-dismiss="modal"><span aria-hidden="true">&times;</span></button>
                <h4 class="modal-title"><?=H(T('添加成员'))?></h4>
            </div>
            <div class="modal-body">
                <form class="form" method="POST" action="">
                    <div class="form-group add-member-username">
                        <label class="text-muted"><?=H(T('输入邮箱:'))?></label>
                        <input type="text" class="form-control" name="username" />
                    </div>
                </form>
            </div>
        </div>
    </div>
</div>

