<div class="modal fade" width="100">
    <div class="modal-dialog">
        <div class="modal-content">
            <div class="modal-header">
                <h4 class="modal-title"><?=H('没有账号?')?>
                <a href="gapper/client/login" class="pull-right">×</a></h4>
            </div>
            <div class="modal-body">
                <h5><?=H('为了完成注册, 需要以下几步简单的操作:')?></h5>
                <div>
                    <p>
                        <h5><?=H('1. 填写注册信息')?></h5>
                        <img src="assets/img/@zh_CN/gapper-no-account/user/signup.png" alt="" width="99%">
                    </p>
                    <p>
                        <h5><?=H('2. 点击最右侧的 "新增应用"')?></h5>
                        <img src="assets/img/@zh_CN/gapper-no-account/user/new-app.png" alt="" width="99%">
                    </p>
                    <p>
                        <h5><?=H('3. 在搜索框中搜索应用')?></h5>
                        <img src="assets/img/@zh_CN/gapper-no-account/user/search-app.png" alt="" width="99%">
                    </p>
                    <p>
                        <h5><?=H('4. 完成应用的添加, 点击应用')?></h5>
                        <img src="assets/img/@zh_CN/gapper-no-account/user/launch-app.png" alt="" width="99%">
                    </p>
                    <p>
                        <h5><?=H('懂了. 去注册')?></h5>
                        <?php 
                            $vGapperURL = rtrim(\Gini\Config::get('gapper.server_home') ?: 'http://gapper.in/', '/');
                            $vSignupURL = $vGapperURL . '/signup';
                        ?>
                        <a href="<?=$vSignupURL?>"><?=$vSignupURL?></a>
                    </p>
                </div>
            </div>
        </div>
    </div>
</div>
