<div class="modal fade">
    <div class="modal-dialog">
        <div class="modal-content">
            <div class="text-center modal-body clearfix" data-gid="<?=H($group)?>" data-callback>
                <button type="button" class="close" data-dismiss="modal"><span aria-hidden="true">&times;</span></button>
            <?php foreach ($data as $key=>$view) {?>
                <?=$view?>
            <?php } ?>
            </div>
        </div>
    </div>
</div>
