<!DOCTYPE html>
<html>
<head>
    <meta charset="utf-8">
    <meta name="renderer" content="webkit">
    <meta name="viewport" content="width=device-width, initial-scale=1.0, user-scalable=no">
    <meta name="gini-locale" content="<?=H(\Gini\Config::get('system.locale'))?>"/>
    <title><?= \Gini\Config::get('site.title') ?></title>
    <base href="<?= H(URL('/')) ?>">
    <?php $addCSS('bootstrap', 'board');?>
    <?php $addCSS('font-awesome', 'board');?>
    <?php $addCSS('bootswatch', 'board');?>
    <?=_G('HEADCSS')?>
    <?=_G('HEADJS')?>
</head>

<body class="<?= $layout_class ?>">
    <?=$body?>
</body>
</html>
