<style>
.gapper-client-dialog .modal-dialog {
    width: 325px;
}
</style>
<ul class="gapper-client-checkbox list-unstyled list-inline text-center">
<?php foreach ($groups as $gid=>$group) {?>
    <li class="gapper-client-checkbox-li" data-gapper-client-group="<?=H($gid)?>"><dl>
        <dt>
            <?php if ($group['icon']) {?>
            <img src="<?=H($group['icon'])?>" />
            <?php } else {?>
            <div class="group-icon-text"><?= H($group['abbr'])?></div>
            <?php }?>
        </dt>
        <dd><?=H($group['title'])?></dd>
    </dl></li>
<?php }?>
</ul>
