<div class="modal fade">
    <div class="modal-dialog">
        <div class="modal-content">
            <div class="modal-header">
                <h4 class="modal-title"><?=H(T('Please Choose Your Group'))?></h4>
            </div>
            <ul class="modal-body gapper-client-checkbox list-unstyled list-inline text-center">
            <?php foreach ($groups as $gid=>$group) {?>
                <li class="gapper-client-checkbox-li" data-gapper-client-group="<?=H($gid)?>"><div class="app-icon app-icon-hoverable" title="<?=H($group['abbr'])?>">
                    <div class="app-icon-image">
                    <?php if ($group['icon']) {?>
                        <img src="<?= H(\Gini\ImageCache::makeURL($group['icon'], 72))?>" data-retina-src="<?= H(\Gini\ImageCache::makeURL($group['icon'], 144))?>" />
                    <?php } else {?>
                        <div class="group-icon-text app-icon-text"><?= H($group['abbr'])?></div>
                    <?php }?>
                    </div>
                    <div class="app-icon-title" title="<?=H($group['abbr'])?>"><?=H($group['abbr'])?></div>
                </div></li>
            <?php }?>
            </ul>
        </div>
    </div>
</div>
