<?php
if (!empty($vars)) {
?>
<script type="text/javascript" charset="utf-8">window.global=window.global||{};window.global.data=<?=J($vars)?>;</script>
<?php
}
?>
<script data-main="<?= H(RURL('main.js', 'js')) ?>" src="<?= H(RURL('require.js', 'js')) ?>"></script>
<!--[if lt IE 9]>
<script src="<?= H(RURL('html5shiv.js', 'js')) ?>"></script>
<script src="<?= H(RURL('respond.js', 'js')) ?>"></script>
<![endif]-->
