<div class="modal fade" width="100">
    <div class="modal-dialog">
        <div class="modal-content">
            <div class="modal-header">
                <h4 class="modal-title"><?=H(T('No account?'))?>
                <a href="gapper/client/login" class="pull-right">×</a></h4>
            </div>
            <div class="modal-body">
                <h5><?=H(T('In order to sign up, you might need a few steps:'))?></h5>
                <div>
                    <p>
                        <h5><?=H(T('1. Fill in the necessary information to sign up'))?></h5>
                        <img src="assets/img/gapper-no-account/group/signup.png" alt="" width="99%">
                    </p>
                    <p>
                        <h5><?=H(T('2. Click the "new group" beneath the avatar'))?></h5>
                        <img src="assets/img/gapper-no-account/group/new-group.png" alt="" width="99%">
                    </p>
                    <p>
                        <h5><?=H(T('3. Fill in the Name, Title and click "add"'))?></h5>
                        <img src="assets/img/gapper-no-account/group/add-group.png" alt="" width="99%">
                    </p>
                    <p>
                        <h5><?=H(T('4. Click "new app", search for the application you want'))?></h5>
                        <img src="assets/img/gapper-no-account/group/search-app.png" alt="" width="99%">
                    </p>
                    <p>
                        <h5><?=H(T('5. There it is, you have installed the app'))?></h5>
                        <img src="assets/img/gapper-no-account/group/launch-app.png" alt="" width="99%">
                    </p>
                    <p>
                        <h5><?=H(T('Get it. Go to sign up'))?></h5>
                        <?php 
                            $vGapperURL = rtrim(\Gini\Config::get('gapper.server_home') ?: 'http://gapper.in/', '/');
                            $vSignupURL = $vGapperURL . '/signup';
                        ?>
                        <a href="<?=$vSignupURL?>"><?=$vSignupURL?></a>
                    </p>
                </div>
            </div>
        </div>
    </div>
</div>
