<div class="modal fade" width="100">
    <div class="modal-dialog">
        <div class="modal-content">
            <div class="modal-header">
                <h4 class="modal-title"><?=H(T('No Account'))?>
                <a href="gapper/client/login" class="pull-right">×</a></h4>
            </div>
            <div class="modal-body">
                <h5><?=H(T('In order to sign up, you might need a few steps'))?></h5>
                <div>
                    <p>
                        <h6><?=H(T('1.Fill in the necessary information to sign up'))?></h6>
                        <img src="<?=H(T('assets/img/gapper-no-account/group/signup.png'))?>" alt="" width="99%">
                    </p>
                    <p>
                        <h6><?=H(T('2.Click the [new group] beneath the avatar'))?></h6>
                        <img src="<?=H(T('assets/img/gapper-no-account/group/new_group.png'))?>" alt="" width="99%">
                    </p>
                    <p>
                        <h6><?=H(T('3.Fill in the Name, Title and click [add].'))?></h6>
                        <img src="<?=H(T('assets/img/gapper-no-account/group/add_group.png'))?>" alt="" width="99%">
                    </p>
                    <p>
                        <h6><?=H(T('4.Click [new app], search for the application you want'))?></h6>
                        <img src="<?=H(T('assets/img/gapper-no-account/group/search_app.png'))?>" alt="" width="99%">
                    </p>
                    <p>
                        <h6><?=H(T('5.There it is, you have installed the app'))?></h6>
                        <img src="<?=H(T('assets/img/gapper-no-account/group/launch_app.png'))?>" alt="" width="99%">
                    </p>
                    <p>
                        <h6><?=H(T('Get it. Go to sign up'))?></h6>
                        <a href="http://gapper.in/signup">http://gapper.in/signup</a>
                    </p>
                </div>
            </div>
        </div>
    </div>
</div>

