<div class="modal fade">
    <div class="modal-dialog modal-gapper-login">
        <div class="modal-content">
            <div class="modal-header">
                <?php if ($hasMultiLogType) {?>
                <button type="button" class="close" data-dismiss="modal"><span aria-hidden="true">&times;</span><span class="sr-only">Close</span></button>
                <?php }?>
                <h4 class="modal-title"><?=H(T('LOGIN'))?></h4>
            </div>
            <form class="modal-body form gapper-auth-form gapper-auth-login-form" method="POST" action="ajax/gapper/auth/gapper/login"><dl class="dl-horizontal">
                <dt class="text-center">
                    <div class="app-icon">
                        <div class="text-center app-icon-image"><img src="<?= H($info->icon) ?>" /></div>
                        <div class="text-center app-icon-title"><?= H($info->name) ?></div>
                    </div>
                </dt>
                <dd>
                    <div class="gapper-auth-login-form-li form-group">
                        <div class="gapper-auth-login-form-placeholder" style="display:none; display/*\**/:block\9;"><?=H(T('Email:'))?></div>
                        <input class="form-control" type="text" name="username" placeholder="<?=H(T('Email'))?>" />
                    </div>
                    <div class="gapper-auth-login-form-li form-group">
                        <div class="gapper-auth-login-form-placeholder" style="display:none; display/*\**/:block\9;"><?=H(T('Password:'))?></div>
                        <input class="form-control" type="password" name="password" placeholder="<?=H(T('Password'))?>" />
                        <div class="text-right">
                            <a href="gapper/client/go-gapper-server/forgot-password" class="text-muted" target="_blank">
                                <small><?= H(T('Forgot password?')) ?></small>
                            </a>
                        </div>
                    </div>
                    <div class="gapper-auth-login-form-li  row form-inline">
                        <div class="col-md-6">
                            <input class="form-control" type="text" name="captcha" placeholder="<?= H(T('captcha')) ?>" />
                        </div>
                        <div class="col-md-6">
                            <img id="captcha_img" border="1" src="<?= \Gini\URI::url('/gapper/client/create-captcha') ?>" width=100 height=30>
                        </div>
                    </div>
                    <br>
                    <div class="gapper-auth-login-form-li form-group">
                        <input class="form-control btn btn-primary" type="submit" value="<?=H(T('Log In'))?>"/>
                    </div>
                    <?php if(\Gini\Config::get('gapper.has_a_guide')) {?>
                    <div class="gapper-auth-login-form-li  form-group text-center text-muted">
                        <a href="gapper/client/no-account"><?=H(T('No account?'))?></a>
                    </div>
                    <?php }?>
                </dd>
            </dl></form>
        </div>
    </div>
</div>

