<div class="modal-header"><?=H(T('LOGIN'))?></div>
<form class="modal-body form gapper-auth-login-form" method="POST" action="ajax/gapper/client/login"><dl class="dl-horizontal">
    <dt class="text-center">
        <div class="app-icon">
            <div class="text-center app-icon-image"><img src="<?=H($info->icon)?>" /></div>
            <div class="text-center app-icon-title"><?=H($info->name)?></div>
        </div>
    </dt>
    <dd>
        <div class="gapper-auth-login-form-li form-group">
            <div class="gapper-auth-login-form-placeholder" style="display:none; display/*\**/:block\9;"><?=H(T('Email:'))?></div>
            <input class="form-control" type="text" name="username" placeholder="<?=H(T('Email'))?>" />
        </div>
        <div class="gapper-auth-login-form-li form-group">
            <div class="gapper-auth-login-form-placeholder" style="display:none; display/*\**/:block\9;"><?=H(T('Password:'))?></div>
            <input class="form-control" type="password" name="password" placeholder="<?=H(T('Password'))?>" />
        </div>
        <div class="gapper-auth-login-form-li form-group"><input class="form-control btn btn-primary" type="submit" /></div>
    </dd>
</dl></form>

