<div class="modal fade">
    <div class="modal-dialog">
        <div class="modal-content">
            <div class="modal-header">
                <h4 class="modal-title"><?=H(T('SIGN UP'))?></h4>
            </div>
            <form class="modal-body form gapper-auth-form gapper-auth-login-form" method="POST" action="ajax/gapper/auth/gapper/signup"><dl class="dl-horizontal">
                <dt class="text-center">
                    <div class="app-icon">
                        <div class="text-center app-icon-image"><img src="<?= H($info->icon) ?>" /></div>
                        <div class="text-center app-icon-title"><?= H($info->name) ?></div>
                    </div>
                </dt>
                <dd>
                    <div class="gapper-auth-login-form-li form-group">
                        <div class="gapper-auth-login-form-placeholder" style="display:none; display/*\**/:block\9;"><?=H(T('Email:'))?></div>
                        <input class="form-control" type="text" name="email" placeholder="<?=H(T('Email'))?>" />
                    </div>
                    <div class="gapper-auth-login-form-li form-group">
                        <div class="gapper-auth-login-form-placeholder" style="display:none; display/*\**/:block\9;"><?=H(T('Full Name:'))?></div>
                        <input class="form-control" type="text" name="name" placeholder="<?=H(T('Full Name'))?>" />
                    </div>
                    <div class="gapper-auth-login-form-li form-group">
                        <div class="gapper-auth-login-form-placeholder" style="display:none; display/*\**/:block\9;"><?=H(T('Password:'))?></div>
                        <input class="form-control" type="password" name="password" placeholder="<?=H(T('Password'))?>" />
                    </div>
                    <div class="gapper-auth-login-form-li form-group">
                        <input class="form-control btn btn-primary" type="submit" value="<?=H(T('Sing Up'))?>"/>
                    </div>
                </dd>
            </dl></form>
        </div>
    </div>
</div>

